opal-elog-parse: correctly parse private header section
Also testing it, although not yet testing parsing all the fields.
We now at least print a notice on unknown version number and attempt
to parse anyway, hopefuly UNKNOWN VERSION gets somebody's attention
that the rest of the information may be rubbish depending on future
versions.

Also fix up printing of create/commit date&time

Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

diff --git a/opal_errd/test-opal-elog-parse b/opal_errd/test-opal-elog-parse
--- a/opal_errd/test-opal-elog-parse
+++ b/opal_errd/test-opal-elog-parse
@@ -27,6 +27,13 @@ if [ $R -ne 234 ]; then
     exit $R
 fi
 
+./opal-elog-parse/opal-elog-parse -d 3 -f $SYSFS/firmware/opal/elog/0x03/raw &>> $LOG 1>&2
+R=$?
+if [ $R -ne 234 ]; then
+    echo 'FAIL:' $R;
+    exit $R
+fi
+
 
 if diff -u test-opal-elog-parse.result $LOG; then
 	rm -rf $SYSFS $OUT $LOG
