opal-elog-parse: Add test case for corrupt section headers
This test case will make opal-elog-parse segfault as it
attempts to parse a corrupted section header and reads past the
end of the error log buffer.

Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

diff --git a/opal_errd/test-opal-elog-parse b/opal_errd/test-opal-elog-parse
--- a/opal_errd/test-opal-elog-parse
+++ b/opal_errd/test-opal-elog-parse
@@ -11,7 +11,22 @@ echo 'test-opal-elog-parse' > $LOG
 ./opal_errd -s $SYSFS -o $OUT/platform -D -e /bin/true 2>&1 \
     | sed -e 's/ELOG\[[0-9]*\]/ELOG[XXXX]/' >> $LOG
 
-./opal-elog-parse/opal-elog-parse -l -f $OUT/platform >> $LOG
+./opal-elog-parse/opal-elog-parse -l -f $OUT/platform &>> $LOG 1>&2
+
+./opal-elog-parse/opal-elog-parse -d 1 -f $OUT/platform &>> $LOG 1>&2
+R=$?
+if [ $R -ne 234 ]; then
+    echo 'FAIL:' $R;
+    exit $R
+fi
+
+./opal-elog-parse/opal-elog-parse -d 2 -f $SYSFS/firmware/opal/elog/0x02/raw &>> $LOG 1>&2
+R=$?
+if [ $R -ne 234 ]; then
+    echo 'FAIL:' $R;
+    exit $R
+fi
+
 
 if diff -u test-opal-elog-parse.result $LOG; then
 	rm -rf $SYSFS $OUT $LOG
