opal-elog-parse: test with a real elog, fixing parsing for remaining sections
We use a real elog data structure as a test case.

this requires us fixing a variety of bugs in parser:
- endian safety of remaining parse_ routines
- stopping parsing sections when we reach number of sections in
  platform header file
- bailing out if platform header is not the first section

We also fix some segfaults on corrupt input

Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

diff --git a/opal_errd/test-opal-elog-parse b/opal_errd/test-opal-elog-parse
--- a/opal_errd/test-opal-elog-parse
+++ b/opal_errd/test-opal-elog-parse
@@ -40,7 +40,15 @@ fi
 # Next log entry is from FSP A, so has 0x50
 ./opal-elog-parse/opal-elog-parse -d 0x50000004 -f $SYSFS/firmware/opal/elog/0x04/raw &>> $LOG 1>&2
 R=$?
-if [ $R -ne 234 ]; then
+if [ $R -ne 0 ]; then
+    echo 'FAIL:' $R;
+    exit $R
+fi
+
+# Our first "real" elog, this should parse 100% successfully
+./opal-elog-parse/opal-elog-parse -d 0x5055ED2E -f $SYSFS/firmware/opal/elog/0x5055ED2E/raw &>> $LOG 1>&2
+R=$?
+if [ $R -ne 0 ]; then
     echo 'FAIL:' $R;
     exit $R
 fi
