test-opal-elog-parse: add tests for fru callout sections
No tests actually examine the output of code added in
f911af0409587e77d98aad6f9d7882ccea929237.

The current test is a truncated raw file from a real fsp dump.
The output was designed to be similar to the output from the fsp
but the test does not compare to real fsp.

[Fixed test-opal_errd.result - Vasant]

Signed-off-by: Cyril Bur <cyril@ozlabs.au.ibm.com>
Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>
Acked-by: Stewart Smith <stewart@linux.vnet.ibm.com>

diff --git a/opal_errd/test-opal-elog-parse b/opal_errd/test-opal-elog-parse
--- a/opal_errd/test-opal-elog-parse
+++ b/opal_errd/test-opal-elog-parse
@@ -15,7 +15,6 @@ echo 'test-opal-elog-parse' > $LOG
 
 # First 3 elogs are completely synthesized and not *entirely* according
 # to spec, but useful in testing.
-
 ./opal-elog-parse/opal-elog-parse -d 1 -f $OUT/platform &>> $LOG 1>&2
 R=$?
 if [ $R -ne 234 ]; then
@@ -62,6 +61,13 @@ if [ $R -ne 0 ]; then
     exit $R
 fi
 
+# Added another test which contains an SRC section with FRU callouts
+./opal-elog-parse/opal-elog-parse -d 0x5034a000 -f $SYSFS/firmware/opal/elog/0x5034a000/raw &>> $LOG 1>&2
+R=$?
+if [ $R -ne 0 ]; then
+    echo 'FAIL:' $R;
+    exit $R
+fi
 
 if diff -u test-opal-elog-parse.result $LOG; then
 	rm -rf $SYSFS $OUT $LOG
