opal_errd: Allow options to rotate_log, add test case
- Command line switches added to specify maximum age and number of logs
- New test case for rotate_logs

[Fixed test case and updated man page - Cyril]

Signed-off-by: Samuel Mendoza-Jonas <sam@ozlabs.au.ibm.com>
Signed-off-by: Cyril Bur <cyril.bur@au1.ibm.com>
Reviewed-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>

diff --git a/opal_errd/test-opal_errd b/opal_errd/test-opal_errd
--- a/opal_errd/test-opal_errd
+++ b/opal_errd/test-opal_errd
@@ -8,15 +8,42 @@ cp -pr sysfs-test/* $SYSFS/
 
 echo "test-opal_errd" > $LOG
 
-./opal_errd -s $SYSFS -o $OUT/platform -D -e /bin/true 2>&1 \
+$VALGRIND ./opal_errd -s $SYSFS -o $OUT/platform -D -e /bin/true 2>&1 \
     | sed -e 's/ELOG\[[0-9]*\]/ELOG[XXXX]/' > $LOG
+R=$?
 
 ls -1 $OUT >> $LOG
 (cd $OUT/platform; md5sum *) | sort  -t ' ' -k 2 | sed 's/ .*-/  /g'  >> $LOG
 
 if diff -u test-opal_errd.result $LOG; then
+	rm -rf $SYSFS/* $OUT/*
+else
+	echo 'FAIL:' $R;
+	exit $R
+fi
+
+
+## Test rotate_logs behaviour ##
+cp -pr sysfs-test/* $SYSFS/
+mkdir -p $OUT/platform
+NAME="$(expr $(date +%s) - $(expr 100 \* 24 \* 60 \* 60))-100days"
+touch $OUT/platform/$NAME
+NAME="$(expr $(date +%s) - $(expr 31 \* 24 \* 60 \* 60))-31days"
+touch $OUT/platform/$NAME
+NAME="$(expr $(date +%s) - $(expr 5 \* 24 \* 60 \* 60))-5days"
+touch $OUT/platform/$NAME
+NAME="$(expr $(date +%s) - $(expr 1 \* 24 \* 60 \* 60))-1days"
+touch $OUT/platform/$NAME
+$VALGRIND ./opal_errd -s $SYSFS -o $OUT/platform -D -e /bin/true -n 10 -a 29  2>&1 \
+        | sed -e 's/ELOG\[[0-9]*\]/ELOG[XXXX]/' > $LOG
+
+ls -1 $OUT >> $LOG
+(cd $OUT/platform; md5sum *) | sort  -t ' ' -k 2 | sed 's/ .*-/  /g'  >> $LOG
+
+if diff -u test-opal_errd.logresult $LOG; then
 	rm -rf $SYSFS $OUT $LOG
 	echo PASS;
 else
-	echo FAIL;
+	echo 'FAIL:' $R;
+	exit $R
 fi
